const actionTypes = Object.freeze({
    //app
    APP_START_UP_COMPLETE: 'APP_START_UP_COMPLETE',
    SET_CONTENT_OF_CONFIRM_MODAL: 'SET_CONTENT_OF_CONFIRM_MODAL',

    //admin
    ADMIN_LOGIN_SUCCESS: 'ADMIN_LOGIN_SUCCESS',
    ADMIN_LOGIN_FAIL: 'ADMIN_LOGIN_FAIL',
    PROCESS_LOGOUT: 'PROCESS_LOGOUT',

    //user
    USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
    USER_LOGIN_FAIL: 'USER_LOGIN_FAIL',
    PROCESS_LOGOUT: 'PROCESS_LOGOUT',

    ADD_USER_SUCCESS: 'ADD_USER_SUCCESS',


    //book
    FETCH_ALL_BOOK_SUCCESS: 'FETCH_ALL_BOOK_SUCCESS',
    FETCH_ALL_BOOK_FAIL: 'FETCH_ALL_BOOK_FAIL',

    CLEARN_ALL_COPY_BOOK: 'CLEARN_ALL_COPY_BOOK',

    ADD_NEW_ITEM_BOOK: 'ADD_NEW_ITEM_BOOK',

    UPDATE_COPY_BOOK: 'UPDATE_COPY_BOOK'

})

export default actionTypes;